import datetime as _dt
from pathlib import Path

import yaml

from resume_tailor_harness.setup.state import WizardState


def _header() -> str:
    today = _dt.date.today().isoformat()
    return (
        f"# Generated by 'resume-tailor-harness setup' on {today}; see README for field documentation\n"
    )


def parse_list(text: str) -> list[str]:
    """Split on commas and newlines; trim; drop blanks.

    Used for the free-text keywords/titles/locations fields in the wizard's
    search screen, where one entry per line or comma-separated both read
    naturally.
    """
    items: list[str] = []
    for chunk in text.replace("\n", ",").split(","):
        item = chunk.strip()
        if item:
            items.append(item)
    return items


def parse_greenhouse_boards(text: str) -> list[dict]:
    """One board per line: ``token`` or ``token, Company Name``."""
    boards: list[dict] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        token, _, company = stripped.partition(",")
        token = token.strip()
        if not token:
            continue
        company = company.strip() or token.title()
        boards.append({"token": token, "company": company})
    return boards


def build_profile_sources(state: WizardState) -> str:
    data = {
        "resume_path": state.resume_path,
        "github_username": state.github_username,
    }
    return _header() + yaml.safe_dump(data, sort_keys=False)


def build_search(state: WizardState) -> str:
    data = {
        "keywords": state.keywords,
        "titles": state.titles,
        "locations": state.locations,
        "remote_policy": [] if state.remote_policy == "any" else [state.remote_policy],
        "min_salary": state.min_salary,
        "yoe_min": state.yoe_min,
        "yoe_max": state.yoe_max,
        "sponsorship_required": state.sponsorship_required,
    }
    return _header() + yaml.safe_dump(data, sort_keys=False)


def build_connectors(state: WizardState) -> str:
    data = {
        "greenhouse": {
            "enabled": state.greenhouse_enabled,
            "boards": state.greenhouse_boards,
        },
        "adzuna": {"enabled": state.adzuna_enabled, "country": state.adzuna_country},
        "remoteok": {"enabled": state.remoteok_enabled},
        "linkedin": {"enabled": state.linkedin_enabled},
    }
    return _header() + yaml.safe_dump(data, sort_keys=False)


def render_from_example(example_path: str | Path) -> str:
    """Return the maintained .example content with a provenance header prepended."""
    body = Path(example_path).read_text(encoding="utf-8")
    return _header() + body
